## This dataset is not an authentic one, rather, it was generated by using the "randbetween" function of microsoft excel. <br>
## The first 25 students' score were generated by using the same formula, with the aim to show some typical results of the science stream students. <br>
## The last 25 students' score were generated by using another formula, with the aim to show some typical results of the art stream students. <br>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files
uploaded = files.upload()

Saving test_result.csv to test_result.csv

In [10]:
import pandas as pd
raw_data = pd.read_csv("test_result.csv")

In [12]:
raw_data

,Student ID,Physics,Biology,Chemistry,Mathematics,History,Geography,English,Literature
1,1,82,51,90,53,80,70,82,81
2,2,72,85,74,69,95,83,47,64
3,3,93,88,96,88,80,92,54,76
4,4,92,100,89,57,42,87,72,72
5,5,50,91,56,89,82,57,84,70
6,6,50,85,57,74,25,30,61,91
7,7,100,95,85,80,94,34,84,75
8,8,51,53,99,59,69,68,47,62
9,9,55,61,60,69,33,84,93,90
10,10,84,92,91,55,41,78,55,73
11,11,69,70,82,98,72,56,63,88
12,12,88,96,79,56,62,37,40,50
13,13,86,75,55,76,98,45,42,91
14,14,87,78,92,84,98,84,49,55
15,15,94,94,73,78,85,55,65,43
16,16,96,56,100,91,58,24,62,76
17,17,93,71,96,69,32,46,80,48
18,18,65,80,53,51,36,100,56,60
19,19,72,57,82,83,54,83,87,66
20,20,94,67,98,92,45,28,99,68
21,21,96,65,75,79,90,89,60,100
22,22,53,87,62,65,69,75,48,54
23,23,50,64,53,60,60,53,62,76
24,24,91,62,76,68,35,56,68,69
25,25,94,51,70,50,71,21,67,64
26,26,69,49,73,6,80,46,71,44
27,27,17,26,77,43,35,76,71,62
28,28,11,16,23,37,83,65,56,88
29,29,36,55,72,30,57,68,81,75
30,30,41,34,48,58,38,44,52,84
31,31,13,74,55,52,63,74,99,66
32,32,53,90,55,56,79,33,99,40
33,33,13,12,44,12,42,12,71,58
34,34,49,54,21,6,47,49,61,86
35,35,51,82,57,49,78,33,80,60
36,36,45,24,63,28,41,23,72,54
37,37,64,46,24,40,61,65,63,90
38,38,58,39,35,31,61,80,63,53
39,39,37,43,49,20,71,62,60,71
40,40,65,65,25,67,47,18,69,67
41,41,48,48,30,79,71,85,64,73
42,42,62,67,42,10,49,50,74,54
43,43,47,51,45,56,83,73,59,50
44,44,48,33,34,36,59,22,97,67
45,45,23,23,29,58,31,80,91,99
46,46,38,56,79,40,81,54,50,98
47,47,10,18,65,5,78,87,87,83
48,48,47,36,57,77,69,36,69,87
49,49,64,88,78,74,56,50,86,52
50,50,50,39,60,37,65,37,97,85

In [11]:
raw_data.index +=1

In [21]:
train_data = raw_data.iloc[:,1:9]

In [22]:
from sklearn.cluster import KMeans 
num_clusters = 2
model = KMeans(init='k-means++', n_clusters=num_clusters, n_init=50)
model.fit(train_data)

KMeans(n_clusters=2, n_init=50)

In [23]:
y = model.predict(train_data)
train_data["cluster"]=y
Group_A = list(train_data[train_data["cluster"]==1].index)
print(f"Group_A = {Group_A}")

Group_A = [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 32, 35, 49]

In [24]:
Group_B = list(train_data[train_data["cluster"]==0].index)
print(f"Group_B = {Group_B}")

Group_B = [9, 23, 26, 27, 28, 29, 30, 31, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50]

# As we can see, the grouping is almost perfect, as most of the science stream students are classified into the same group.
# Also, most art students are classified into another group.